import type { Lang, SymbolId } from "./types";

export const COPY = {
  de: {
    title: "Book of Ra",
    subtitle: "6 Rollen · 25 Linien",
    tapToEnter: "Berühren, um das Grab zu betreten",
    loading: "Das Grab öffnet sich …",
    credits: "Guthaben",
    bet: "Einsatz",
    win: "Gewinn",
    line: "Linie",
    lines: "Linien",
    betPerLine: "Einsatz / Linie",
    start: "Start",
    stop: "Stop",
    auto: "Auto",
    turbo: "Turbo",
    buy: "Kaufen",
    buyTitle: "Feature kaufen",
    buyFsTitle: "Freispiele kaufen",
    buyFsBody: "Die Walzen drehen und zeigen mindestens 3 Bücher. 3 / 4 / 5 / 6 Bücher → 10 / 15 / 25 / 30 Freispiele.",
    buyFsCost: "100× Einsatz",
    buyExpandTitle: "Expand-Symbol",
    buyExpandBody:
      "Wähle ein Symbol. Jeder Spin kostet das 10-fache. Ab 2 Walzen klappen Karten nach oben und unten auf. Bleibt an, bis du es ausstellst oder das Guthaben nicht reicht.",
    buyExpandCost: "10× Einsatz",
    buyPick: "Symbol wählen",
    buyArmed: "Expand",
    buyOff: "Deaktivieren",
    expandOff: "Expand aus — Guthaben reicht nicht",
    paytable: "Gewinnplan",
    settings: "Einstellungen",
    language: "Sprache",
    sound: "Ton",
    on: "An",
    off: "Aus",
    reload: "Aufladen",
    depositTitle: "Konto aufladen",
    depositBody: "Zahle per TWINT oder bar. Der Betrag kommt aufs Konto, sobald der Betreiber bestätigt.",
    depositTwint: "TWINT",
    depositCash: "Bar",
    depositSend: "Zahlung gemeldet",
    depositPending: "Warten auf Gutschrift",
    depositTwintHint: "Betrag an diese TWINT-Nummer senden, danach hier bestätigen.",
    depositCashHint: "Betrag bar übergeben. Der Betreiber bucht danach.",
    depositNoTwint: "TWINT-Nummer legt der Betreiber unter Freigaben fest.",
    gamble: "Risiko",
    collect: "Nehmen",
    red: "Rot",
    black: "Schwarz",
    gambleHint: "Rot oder Schwarz — Gewinn verdoppeln",
    freeSpins: "Freispiele",
    specialSymbol: "Sondersymbol",
    bonusTitle: "Freispiele",
    bonusBody: "Freispiele mit expandierendem Symbol",
    retrigger: "Freispiele verlängert",
    stackTitle: "Weiteres Sondersymbol",
    stackBody: "Drei Bücher. Wähle ein Symbol — es kommt auf den Stapel und expandiert mit.",
    stacked: "Stapel",
    pickHint: "Tippen zum Wählen",
    fsTotal: "Freispiele",
    fsTotalSub: "Totalgewinn",
    greatWin: "Großer Gewinn",
    megaWin: "Mega-Gewinn",
    epicWin: "Legendärer Gewinn",
    scatter: "Scatter",
    wild: "Wild + Scatter",
    ofAKind: "gleicher Symbole",
    close: "Schließen",
    autoTitle: "Automatik",
    autoSpins: "Runden",
    stopBonus: "Stopp bei Freispielen",
    spaceHint: "Leertaste = Start",
    broke: "Guthaben reicht nicht — Aufladen oder Einsatz senken",
    biggest: "Bester Gewinn",
    picturePays: "Bildsymbole",
    royalPays: "Kartensymbole",
    linesTitle: "Gewinnlinien",
    rulesTitle: "Regeln",
    rule1: "6 Walzen, 4 Reihen, bis zu 25 Gewinnlinien. Auszahlung von links nach rechts.",
    rule2: "Das goldene Totenbuch ersetzt alle Symbole und zahlt als Scatter überall. Ab 3 Büchern klappt es auf.",
    rule3: "3 Bücher: 10 Freispiele, 4: 15, 5: 25, 6: 30. Im Bonus weitere Bücher: extra Freispiele und ein weiteres Symbol auf den Stapel.",
    rule4: "Sondersymbole expandieren erst ab 2 Walzen — eine Walze zahlt nicht. Gestapelte Symbole zahlen einzeln.",
    rule5: "Nach einem Gewinn: Risiko auf Rot oder Schwarz, bis zu 5 Mal.",
    rule6: "Freispiele kaufen (100×): garantiert mindestens 3 Bücher, dann 10 / 15 / 25 / 30 Freispiele. Expand-Symbol 10× pro Spin.",
    symbols: {
      book: "Totenbuch",
      explorer: "Entdecker",
      priestess: "Priesterin",
      ankh: "Ankh",
      anubis: "Anubis",
      statue: "Statue",
      scarab: "Skarabäus",
      ace: "Ass",
      king: "König",
      queen: "Dame",
      jack: "Bube",
      ten: "Zehn",
    } satisfies Record<SymbolId, string>,
  },
  en: {
    title: "Book of Ra",
    subtitle: "6 Reels · 25 Lines",
    tapToEnter: "Touch to enter the tomb",
    loading: "The tomb is opening …",
    credits: "Credits",
    bet: "Bet",
    win: "Win",
    line: "Line",
    lines: "Lines",
    betPerLine: "Bet / line",
    start: "Start",
    stop: "Stop",
    auto: "Auto",
    turbo: "Turbo",
    buy: "Buy",
    buyTitle: "Buy a feature",
    buyFsTitle: "Buy free spins",
    buyFsBody: "The reels spin and show at least 3 books. 3 / 4 / 5 / 6 books → 10 / 15 / 25 / 30 free spins.",
    buyFsCost: "100× bet",
    buyExpandTitle: "Expanding symbol",
    buyExpandBody:
      "Pick a symbol. Every spin costs 10× the bet. From 2 reels, cards fold out up and down. Stays on until you turn it off or credits run out.",
    buyExpandCost: "10× bet",
    buyPick: "Choose a symbol",
    buyArmed: "Expand",
    buyOff: "Turn off",
    expandOff: "Expand off — not enough credits",
    paytable: "Paytable",
    settings: "Settings",
    language: "Language",
    sound: "Sound",
    on: "On",
    off: "Off",
    reload: "Top up",
    depositTitle: "Top up",
    depositBody: "Pay by TWINT or cash. Credits land after the host confirms.",
    depositTwint: "TWINT",
    depositCash: "Cash",
    depositSend: "I've paid",
    depositPending: "Waiting for credit",
    depositTwintHint: "Send the amount to this TWINT number, then confirm here.",
    depositCashHint: "Hand over the cash. The host will credit you after.",
    depositNoTwint: "The host sets the TWINT number under Approvals.",
    gamble: "Gamble",
    collect: "Collect",
    red: "Red",
    black: "Black",
    gambleHint: "Red or black — double the win",
    freeSpins: "Free spins",
    specialSymbol: "Special symbol",
    bonusTitle: "Free spins",
    bonusBody: "free spins with an expanding symbol",
    retrigger: "Free spins extended",
    stackTitle: "Another special symbol",
    stackBody: "Three books. Pick a symbol — it joins the stack and expands with the others.",
    stacked: "Stack",
    pickHint: "Tap to choose",
    fsTotal: "Free Spins",
    fsTotalSub: "Total Win",
    greatWin: "Great win",
    megaWin: "Mega win",
    epicWin: "Legendary win",
    scatter: "Scatter",
    wild: "Wild + Scatter",
    ofAKind: "of a kind",
    close: "Close",
    autoTitle: "Autoplay",
    autoSpins: "Rounds",
    stopBonus: "Stop on free spins",
    spaceHint: "Space = Start",
    broke: "Not enough credits — top up or lower the bet",
    biggest: "Best win",
    picturePays: "Picture symbols",
    royalPays: "Card symbols",
    linesTitle: "Paylines",
    rulesTitle: "Rules",
    rule1: "6 reels, 4 rows, up to 25 paylines. Wins count left to right.",
    rule2: "The golden Book of the Dead substitutes for every symbol and pays as scatter anywhere. From 3 books it opens and turns its pages.",
    rule3: "3 books: 10 free spins, 4: 15, 5: 25, 6: 30. More books in the bonus: extra spins and another stacked symbol.",
    rule4: "Special symbols expand only from 2 reels — a single reel does not pay. Stacked symbols pay separately.",
    rule5: "After a win: gamble red or black, up to 5 times.",
    rule6: "Buy free spins (100×): at least 3 books guaranteed, then 10 / 15 / 25 / 30 free spins. Expanding symbol 10× per spin.",
    symbols: {
      book: "Book of the Dead",
      explorer: "Explorer",
      priestess: "Priestess",
      ankh: "Ankh",
      anubis: "Anubis",
      statue: "Statue",
      scarab: "Scarab",
      ace: "Ace",
      king: "King",
      queen: "Queen",
      jack: "Jack",
      ten: "Ten",
    } satisfies Record<SymbolId, string>,
  },
} as const;

export function t(lang: Lang) {
  return COPY[lang];
}
