/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApproveRouteImport } from './routes/approve'
import { Route as BookRouteImport } from './routes/book'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RamonRouteImport } from './routes/ramon'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as ApiGamesRouteImport } from './routes/api/games'
import { Route as ApiPlayersRouteImport } from './routes/api/players'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGamesLatestRouteImport } from './routes/api/games.latest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveRoute = ApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RamonRoute = RamonRouteImport.update({
  id: '/ramon',
  path: '/ramon',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersRoute = ApiPlayersRouteImport.update({
  id: '/api/players',
  path: '/api/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesLatestRoute = ApiGamesLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => ApiGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approve': typeof ApproveRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ramon': typeof RamonRoute
  '/reset': typeof ResetRoute
  '/roulette': typeof RouletteRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/api/players': typeof ApiPlayersRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games/latest': typeof ApiGamesLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approve': typeof ApproveRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ramon': typeof RamonRoute
  '/reset': typeof ResetRoute
  '/roulette': typeof RouletteRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/api/players': typeof ApiPlayersRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games/latest': typeof ApiGamesLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approve': typeof ApproveRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ramon': typeof RamonRoute
  '/reset': typeof ResetRoute
  '/roulette': typeof RouletteRoute
  '/api/games': typeof ApiGamesRouteWithChildren
  '/api/players': typeof ApiPlayersRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games/latest': typeof ApiGamesLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approve'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/ramon'
    | '/reset'
    | '/roulette'
    | '/api/games'
    | '/api/players'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/games/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approve'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/ramon'
    | '/reset'
    | '/roulette'
    | '/api/games'
    | '/api/players'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/games/latest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approve'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/ramon'
    | '/reset'
    | '/roulette'
    | '/api/games'
    | '/api/players'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/games/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApproveRoute: typeof ApproveRoute
  BookRoute: typeof BookRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RamonRoute: typeof RamonRoute
  ResetRoute: typeof ResetRoute
  RouletteRoute: typeof RouletteRoute
  ApiGamesRoute: typeof ApiGamesRouteWithChildren
  ApiPlayersRoute: typeof ApiPlayersRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve': {
      id: '/approve'
      path: '/approve'
      fullPath: '/approve'
      preLoaderRoute: typeof ApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramon': {
      id: '/ramon'
      path: '/ramon'
      fullPath: '/ramon'
      preLoaderRoute: typeof RamonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players': {
      id: '/api/players'
      path: '/api/players'
      fullPath: '/api/players'
      preLoaderRoute: typeof ApiPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/latest': {
      id: '/api/games/latest'
      path: '/latest'
      fullPath: '/api/games/latest'
      preLoaderRoute: typeof ApiGamesLatestRouteImport
      parentRoute: typeof ApiGamesRoute
    }
  }
}

interface ApiGamesRouteChildren {
  ApiGamesLatestRoute: typeof ApiGamesLatestRoute
}

const ApiGamesRouteChildren: ApiGamesRouteChildren = {
  ApiGamesLatestRoute: ApiGamesLatestRoute,
}

const ApiGamesRouteWithChildren = ApiGamesRoute._addFileChildren(
  ApiGamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApproveRoute: ApproveRoute,
  BookRoute: BookRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RamonRoute: RamonRoute,
  ResetRoute: ResetRoute,
  RouletteRoute: RouletteRoute,
  ApiGamesRoute: ApiGamesRouteWithChildren,
  ApiPlayersRoute: ApiPlayersRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
